name: Rust

on:
  push:
    branches: [ pure_x11rb ]
  pull_request:
    branches: [ pure_x11rb ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --target x86_64-unknown-linux-musl --verbose
    - name: Run tests
      run: cargo test --verbose
